/* =========================================================
   CONFIGURAÇÃO — edite aqui seus dados de contato
   ========================================================= */
const CONFIG = {
  nome: "Seu Nome",
  estudio: "Estúdio",
  cidade: "São Paulo · SP",
  whatsapp: "5511999999999", // DDI + DDD + número, só dígitos
  instagram: "seuperfil",
  email: "contato@seudominio.com.br",
};

/* =========================================================
   CATEGORIAS DE MOVIMENTO
   ========================================================= */
const MOVE_CATS = {
  pan: "Pan / Tilt",
  zoom: "Zoom / Lente",
  dolly: "Dolly / Tracking",
  fisico: "Movimentos físicos",
  humano: "Câmera humana",
  drone: "Drone / Grua",
  especial: "Especiais",
};

/* =========================================================
   46 MOVIMENTOS DE CÂMERA
   p = preset da animação · uso = quando usar (PT) · en = prompt
   ========================================================= */
const MOVES = [
  // PAN / TILT
  { id: "01", cat: "pan", p: "static", pt: "Plano estático",
    uso: "Deixa a ação respirar. Ótimo para produto em destaque e fala para a câmera.",
    en: "locked-off static shot. Movement: the camera stays completely fixed on a tripod for the whole clip. Speed: no camera motion at all. Framing: same angle, height and lens throughout; only the subject and scene elements move. End: identical framing to the first frame." },
  { id: "02", cat: "pan", p: "panR", pt: "Pan para a direita",
    uso: "Revela o espaço ao lado sem mudar o ponto de vista. Bom para apresentar o cenário.",
    en: "pan right. Movement: the camera rotates horizontally to the right on a fixed tripod head, without changing position. Speed: slow, even rotation. Framing: the horizon stays level as new space is revealed on the right. End: rests on a balanced final composition." },
  { id: "02B", cat: "pan", p: "panL", pt: "Pan para a esquerda",
    uso: "O mesmo giro no sentido oposto. Use para guiar o olhar de volta a um assunto.",
    en: "pan left. Movement: the camera rotates horizontally to the left on a fixed tripod head, without changing position. Speed: slow, even rotation. Framing: the horizon stays level as new space is revealed on the left. End: rests on a balanced final composition." },
  { id: "03", cat: "pan", p: "whipR", pt: "Whip pan direita",
    uso: "Transição com energia: um giro rápido que borra e aterrissa no próximo assunto.",
    en: "whip pan right. Movement: a sudden, very fast horizontal rotation to the right from a fixed position. Speed: explosive, with strong motion blur mid-move. Framing: starts on a clear composition and snaps onto a new subject. End: lands sharp and stable on the new subject." },
  { id: "03B", cat: "pan", p: "whipL", pt: "Whip pan esquerda",
    uso: "Mesmo corte seco no sentido contrário. Funciona muito bem em sequência de cortes.",
    en: "whip pan left. Movement: a sudden, very fast horizontal rotation to the left from a fixed position. Speed: explosive, with strong motion blur mid-move. Framing: starts on a clear composition and snaps onto a new subject. End: lands sharp and stable on the new subject." },
  { id: "04", cat: "pan", p: "tiltU", pt: "Tilt para cima",
    uso: "Mostra altura e imponência: de baixo para cima em prédios, pessoas e garrafas.",
    en: "tilt up. Movement: the camera pivots upward on a fixed head, without changing position. Speed: smooth, steady tilt. Framing: keeps the vertical subject centered as the frame travels up. End: settles on the top of the subject or the sky." },
  { id: "04B", cat: "pan", p: "tiltD", pt: "Tilt para baixo",
    uso: "Parte do céu ou do topo e desce até o assunto. Abertura de cena clássica.",
    en: "tilt down. Movement: the camera pivots downward on a fixed head, without changing position. Speed: smooth, steady tilt. Framing: keeps the vertical subject centered as the frame travels down. End: settles on the subject at the bottom of the move." },

  // ZOOM / LENTE
  { id: "05", cat: "zoom", p: "zoomInS", pt: "Zoom in lento",
    uso: "Aumenta a tensão aos poucos, sem mover a câmera. Revelação sutil e suspense.",
    en: "slow zoom in. Movement: the lens slowly increases focal length while the camera stays in place. Speed: gradual and constant. Framing: the main subject grows in frame and stays centered, with flat perspective. End: holds on a tighter, stable composition." },
  { id: "05B", cat: "zoom", p: "zoomOutS", pt: "Zoom out lento",
    uso: "Abre o contexto devagar e revela onde o assunto está.",
    en: "slow zoom out. Movement: the lens slowly decreases focal length while the camera stays in place. Speed: gradual and constant. Framing: the subject stays readable as more surroundings appear. End: holds on a wider, stable composition." },
  { id: "06", cat: "zoom", p: "zoomInF", pt: "Zoom in rápido",
    uso: "Aponta um detalhe num instante: logotipo, textura, expressão.",
    en: "fast zoom in. Movement: the lens quickly increases focal length toward the subject. Speed: quick and decisive. Framing: the subject stays centered through the scale change. End: holds on a tight, stable composition." },
  { id: "06B", cat: "zoom", p: "zoomOutF", pt: "Zoom out rápido",
    uso: "Sai do detalhe e mostra o todo de uma vez. Bom para humor e surpresa.",
    en: "fast zoom out. Movement: the lens quickly decreases focal length away from the subject. Speed: quick and decisive. Framing: the subject stays readable as the environment appears. End: holds on a wide, stable composition." },
  { id: "07A", cat: "zoom", p: "crashIn", pt: "Crash zoom in",
    uso: "Impacto e humor: zoom brusco, quase um soco visual.",
    en: "crash zoom in. Movement: an abrupt, violent zoom toward the subject. Speed: near-instant and punchy. Framing: the subject stays readable while the scale jumps. End: slams into a tight, bold close-up." },
  { id: "07B", cat: "zoom", p: "crashOut", pt: "Crash zoom out",
    uso: "Recuo brusco que revela o absurdo da situação ou a escala do lugar.",
    en: "crash zoom out. Movement: an abrupt, violent zoom away from the subject. Speed: near-instant and punchy. Framing: the subject stays readable as the surroundings burst into view. End: lands on a bold wide composition." },

  // DOLLY / TRACKING
  { id: "08", cat: "dolly", p: "dollyIn", pt: "Dolly in",
    uso: "Aproxima de verdade: cria intimidade e muda a perspectiva (o fundo cresce menos que o assunto).",
    en: "dolly in. Movement: the camera physically travels forward on a straight track toward the subject. Speed: smooth, controlled push. Framing: height and lens direction stay constant; foreground and background shift with natural parallax. End: finishes closer, in a tighter composition." },
  { id: "09", cat: "dolly", p: "dollyOut", pt: "Dolly out",
    uso: "Afasta e isola o assunto. Clássico de final e de sensação de solidão.",
    en: "dolly out. Movement: the camera physically travels backward on a straight track away from the subject. Speed: smooth, controlled retreat. Framing: height and lens direction stay constant as more of the environment enters frame. End: finishes on a wider composition." },
  { id: "16", cat: "dolly", p: "tracking", pt: "Tracking",
    uso: "Acompanha o assunto em movimento, sempre à mesma distância.",
    en: "tracking shot. Movement: the camera moves through the scene alongside the moving subject. Speed: matches the subject's pace exactly. Framing: the subject stays consistently framed while the environment flows past. End: continues the moving composition." },
  { id: "17", cat: "dolly", p: "follow", pt: "Follow / sobre o ombro",
    uso: "Segue por trás: o público vê o que o personagem vê.",
    en: "follow shot from behind. Movement: the camera follows the subject from behind at shoulder height. Speed: matches their walking pace. Framing: the back of the head and shoulders anchor the foreground while the path ahead stays visible. End: keeps following with the subject leading." },
  { id: "18", cat: "dolly", p: "reverse", pt: "Tracking reverso",
    uso: "A câmera recua na frente de quem anda. Perfeito para fala e depoimento (walk-and-talk).",
    en: "reverse tracking shot. Movement: the camera moves backward in front of the subject as they walk toward it. Speed: matches their forward pace. Framing: face and upper body stay steady while the background recedes. End: holds a stable front-facing moving frame." },
  { id: "19", cat: "dolly", p: "side", pt: "Tracking lateral",
    uso: "Anda em paralelo ao assunto, de perfil. Muito usado em moda e esporte.",
    en: "side tracking shot. Movement: the camera travels parallel to the subject along their path. Speed: matches the subject. Framing: the subject in profile or three-quarter view at a constant distance. End: continues the lateral motion." },
  { id: "20", cat: "dolly", p: "low", pt: "Tracking baixo",
    uso: "Na altura do chão: pés, rodas, patas. Dá peso e velocidade.",
    en: "low tracking shot. Movement: the camera travels close to the ground alongside the subject. Speed: matches footsteps or wheels. Framing: low angle with the ground rushing through the frame. End: keeps the low perspective throughout." },
  { id: "21", cat: "dolly", p: "vehicle", pt: "Tracking de veículo",
    uso: "Carro de câmera ao lado do veículo: a estrada passa, o carro fica estável.",
    en: "vehicle tracking shot. Movement: the camera travels with the vehicle along the road. Speed: matches the vehicle. Framing: the vehicle stays locked in frame while the road and scenery stream past. End: maintains a steady moving composition." },
  { id: "22", cat: "dolly", p: "chase", pt: "Perseguição",
    uso: "Rápido, próximo e reativo: urgência e adrenalina.",
    en: "chase shot. Movement: the camera pursues the subject closely and aggressively. Speed: fast and reactive, with slight instability. Framing: the subject stays visible with energetic reframing. End: remains close to the action." },

  // MOVIMENTOS FÍSICOS
  { id: "10", cat: "fisico", p: "truckR", pt: "Truck para a direita",
    uso: "A câmera anda de lado e cria parallax forte entre o primeiro plano e o fundo.",
    en: "truck right. Movement: the whole camera travels sideways to the right on a straight path, lens facing forward. Speed: constant lateral speed. Framing: the foreground passes faster than the background, creating depth. End: settles on a new lateral composition." },
  { id: "10B", cat: "fisico", p: "truckL", pt: "Truck para a esquerda",
    uso: "O mesmo deslocamento lateral no sentido oposto.",
    en: "truck left. Movement: the whole camera travels sideways to the left on a straight path, lens facing forward. Speed: constant lateral speed. Framing: the foreground passes faster than the background, creating depth. End: settles on a new lateral composition." },
  { id: "11A", cat: "fisico", p: "pedUp", pt: "Pedestal para cima",
    uso: "Sobe a câmera inteira sem inclinar. Ótimo para revelar o produto sobre a mesa.",
    en: "pedestal up. Movement: the entire camera rises vertically in a straight line, lens kept level. Speed: smooth, even lift. Framing: no tilt; the scene slides down in frame. End: settles at a higher, level viewpoint." },
  { id: "11B", cat: "fisico", p: "pedDown", pt: "Pedestal para baixo",
    uso: "Desce na vertical até a altura do assunto. Bom para aterrissar num detalhe.",
    en: "pedestal down. Movement: the entire camera lowers vertically in a straight line, lens kept level. Speed: smooth, even descent. Framing: no tilt; the scene slides up in frame. End: settles at a lower, level viewpoint." },
  { id: "12", cat: "fisico", p: "sliderR", pt: "Slider para a direita",
    uso: "Deslize curto e elegante: o favorito de still de produto e de food.",
    en: "slider right. Movement: a short, precise lateral slide to the right. Speed: slow and silky. Framing: subtle parallax between foreground, product and background. End: settles on a refined composition with a slightly new angle." },
  { id: "12B", cat: "fisico", p: "sliderL", pt: "Slider para a esquerda",
    uso: "O mesmo deslize no sentido oposto. Use dois takes para ter opções na edição.",
    en: "slider left. Movement: a short, precise lateral slide to the left. Speed: slow and silky. Framing: subtle parallax between foreground, product and background. End: settles on a refined composition with a slightly new angle." },
  { id: "13", cat: "fisico", p: "pushPast", pt: "Push past",
    uso: "Passa rente a um objeto em primeiro plano e revela a cena por trás.",
    en: "push past. Movement: the camera glides forward, brushing past a foreground object close to the lens. Speed: smooth forward glide. Framing: the foreground element sweeps out of frame as the scene behind becomes clear. End: arrives beyond the foreground on the subject." },
  { id: "14", cat: "fisico", p: "arcR", pt: "Arco para a direita",
    uso: "Meia-volta curta em torno do assunto: dá volume sem perder o foco.",
    en: "arc right. Movement: the camera travels on a shallow curve around the subject toward the right. Speed: measured and smooth. Framing: distance and height stay constant; the subject remains centered while the angle changes. End: settles on a new right-side angle." },
  { id: "14B", cat: "fisico", p: "arcL", pt: "Arco para a esquerda",
    uso: "O mesmo arco no sentido oposto. Ótimo para mostrar o outro lado do produto.",
    en: "arc left. Movement: the camera travels on a shallow curve around the subject toward the left. Speed: measured and smooth. Framing: distance and height stay constant; the subject remains centered while the angle changes. End: settles on a new left-side angle." },
  { id: "15", cat: "fisico", p: "orbitCW", pt: "Órbita horária",
    uso: "Volta completa em torno do assunto: o fundo gira e o assunto fica. Clássico de produto herói.",
    en: "clockwise orbit. Movement: the camera circles clockwise around the subject at a constant radius. Speed: smooth, continuous orbit. Framing: the subject stays centered while the background rotates behind it. End: completes the arc with stable framing." },
  { id: "15B", cat: "fisico", p: "orbitCCW", pt: "Órbita anti-horária",
    uso: "A mesma órbita no sentido contrário. Alterne as duas numa sequência de cortes.",
    en: "counterclockwise orbit. Movement: the camera circles counterclockwise around the subject at a constant radius. Speed: smooth, continuous orbit. Framing: the subject stays centered while the background rotates behind it. End: completes the arc with stable framing." },

  // CÂMERA HUMANA
  { id: "23", cat: "humano", p: "handheld", pt: "Câmera na mão",
    uso: "Movimento humano e orgânico. Passa verdade: documental, bastidores, lifestyle.",
    en: "handheld shot. Movement: the camera is held by an operator with natural body movement. Speed: responsive and organic. Framing: subtle sway and micro-corrections while the subject stays readable. End: a natural, slightly imperfect final frame." },
  { id: "24", cat: "humano", p: "snorri", pt: "Snorricam",
    uso: "Câmera presa ao corpo: o personagem fica fixo e o mundo balança à volta.",
    en: "body-mounted Snorricam shot. Movement: the camera is rigged to the subject's body, facing them. Speed: follows the subject's body motion. Framing: the subject stays locked and centered while the background sways and shifts around them. End: the subject is still locked in frame." },

  // DRONE / GRUA
  { id: "25", cat: "drone", p: "craneUp", pt: "Grua subindo",
    uso: "Sobe e revela a escala do lugar. Ótimo para encerramento.",
    en: "crane up. Movement: the camera rises smoothly through open space on a crane. Speed: slow, graceful ascent. Framing: the subject remains readable as more of the location is revealed below. End: settles on a high, wide view." },
  { id: "25B", cat: "drone", p: "craneDown", pt: "Grua descendo",
    uso: "Desce do alto até o assunto. Abertura clássica de filme.",
    en: "crane down. Movement: the camera descends smoothly through open space on a crane. Speed: slow, graceful descent. Framing: the location narrows as the camera arrives at the subject. End: settles at eye level on the subject." },
  { id: "26", cat: "drone", p: "droneIn", pt: "Drone avançando",
    uso: "Voa em direção ao destino: apresentação de lugar, empreendimento ou evento.",
    en: "drone push in. Movement: an aerial camera flies smoothly forward toward the subject or destination. Speed: steady aerial glide. Framing: the destination stays centered as the camera approaches. End: arrives on a closer aerial composition." },
  { id: "26B", cat: "drone", p: "droneOut", pt: "Drone recuando",
    uso: "Afasta e mostra a imensidão em volta.",
    en: "drone pull back. Movement: an aerial camera flies smoothly backward away from the subject. Speed: steady aerial retreat. Framing: the subject stays centered as the landscape expands around it. End: finishes on a wide aerial composition." },
  { id: "27", cat: "drone", p: "heli", pt: "Plano de helicóptero",
    uso: "Muito alto, amplo e lento: épico, paisagem, abertura de filme.",
    en: "helicopter aerial shot. Movement: a high-altitude camera travels along a wide, slow flight path. Speed: steady and majestic. Framing: the landscape dominates, with any subject small in frame. End: a stable, high wide view." },

  // ESPECIAIS
  { id: "S1", cat: "especial", p: "fpv", pt: "Primeira pessoa (POV)",
    uso: "O espectador vira o personagem. Ótimo para mostrar a experiência com o produto.",
    en: "first-person POV shot. Movement: the camera moves forward at eye height as if it were the character's eyes. Speed: natural walking pace with a gentle bob. Framing: hands or arms may enter the frame as reference. End: arrives at the next point of interest from the same POV." },
  { id: "S2", cat: "especial", p: "tiltshift", pt: "Tilt-shift",
    uso: "Efeito maquete: a cena real parece uma miniatura.",
    en: "tilt-shift miniature effect. Movement: a gentle high-angle drift over the scene. Speed: slow and precise. Framing: a narrow horizontal band of sharp focus with strong blur above and below, saturated colors. End: the miniature illusion holds." },
  { id: "S3", cat: "especial", p: "infinite", pt: "Zoom infinito",
    uso: "Mergulha num ponto e sai em outro mundo. Transição hipnótica.",
    en: "infinite zoom. Movement: a continuous zoom into the exact center of the frame. Speed: smooth and accelerating. Framing: the center point stays locked as it expands. End: a new scene fills the frame from inside the center point." },
  { id: "S4", cat: "especial", p: "earth", pt: "Zoom out até o planeta",
    uso: "Do chão ao planeta num único movimento. Escala máxima.",
    en: "earth zoom out. Movement: the camera pulls up from street level through city, region and continent to space. Speed: rapid, accelerating ascent. Framing: the starting point stays centered as the scale expands. End: a planet-scale view of Earth." },
  { id: "S5", cat: "especial", p: "timelapse", pt: "Time-lapse",
    uso: "Câmera parada, tempo acelerado: nuvens, luzes, multidões.",
    en: "locked-off time-lapse. Movement: the camera is completely fixed while time passes rapidly. Speed: fast time compression, clouds and light racing. Framing: same composition from start to end. End: same angle showing a clear change of time of day." },
  { id: "S6", cat: "especial", p: "passThrough", pt: "Atravessar objetos",
    uso: "Passa por dentro de janelas, portas, telas e garrafas: transição criativa.",
    en: "pass-through shot. Movement: the camera flies forward toward an opening or surface and passes straight through it. Speed: smooth, centered glide. Framing: the opening stays centered as it grows to fill the frame. End: arrives inside the space beyond." },
];

/* =========================================================
   TÉCNICAS DE FOTOGRAFIA — publicidade, editorial, composição
   lights: a = ângulo (0 = lado da câmera, 180 = atrás, negativo = esquerda)
           el = altura (-1 baixo … 1 alto) · t = tipo · c = cor · r = distância
   ========================================================= */
const TECH_CATS = {
  produto: "Luz de produto",
  editorial: "Editorial & retrato",
  composicao: "Composição",
};

const TECHS = [
  /* ---------------- PRODUTO ---------------- */
  { id: "P1", cat: "produto", nome: "Hero shot em 3 pontos", bg: "grad",
    quando: "É a foto principal de campanha e de e-commerce premium: dá volume, separa o produto do fundo e tem cara de anúncio.",
    passos: ["Principal: softbox grande a 45°, um pouco acima do produto.", "Rebatedor branco do lado oposto para abrir as sombras.", "Strip atrás e de lado para desenhar a borda e separar do fundo."],
    dica: "Aproxime a softbox. Quanto maior a fonte em relação ao produto, mais suave a luz.",
    lights: [{ a: -45, el: .6, t: "soft", n: "Principal" }, { a: 65, el: 0, t: "refl", n: "Rebatedor" }, { a: 155, el: .3, t: "strip", n: "Contorno" }],
    light: "three-point studio lighting: large softbox key at 45 degrees, white bounce fill, strip-light rim separating the product from the background",
    prompt: "Premium advertising hero shot of a [product] on a matte pedestal, three-point studio lighting with a large softbox key at 45 degrees, soft white fill and a crisp strip-light rim, subtle gradient backdrop, razor-sharp detail, commercial product photography, 100mm macro lens, f/11" },
  { id: "P2", cat: "produto", nome: "Dark field: contorno em vidro", bg: "black",
    quando: "Vidro, perfume, destilados e metal. Bordas brilhantes desenham o produto sobre fundo preto, com muito luxo e pouco reflexo.",
    passos: ["Fundo preto e sala escura.", "Duas strips atrás do produto, uma de cada lado, apontando para as bordas.", "Nenhuma luz frontal: o contorno faz todo o desenho."],
    dica: "Recorte cartões pretos no formato do rótulo para controlar reflexos indesejados.",
    lights: [{ a: -150, el: 0, t: "strip", n: "Strip esq." }, { a: 150, el: 0, t: "strip", n: "Strip dir." }],
    light: "dark-field lighting: two tall strip lights behind on both sides tracing bright edge highlights, no front light, pure black background",
    prompt: "Luxury glass [perfume bottle] on black, dark-field lighting with two tall strip lights behind tracing thin bright edge highlights along the glass contours, deep black background, glossy reflections, high-end fragrance advertising, 100mm macro, f/16" },
  { id: "P3", cat: "produto", nome: "Bright field: vidro no claro", bg: "white",
    quando: "Vidros e líquidos transparentes com contorno escuro e definido sobre um fundo luminoso. Visual limpo, científico, farmacêutico.",
    passos: ["Uma luz atrás, atravessando um difusor ou papel vegetal.", "Bandeiras pretas nas laterais, fora do quadro, para desenhar as bordas escuras.", "Produto a alguns palmos do fundo iluminado."],
    dica: "Quanto mais longe o produto está do fundo, mais grossa fica a linha escura da borda.",
    lights: [{ a: 180, el: 0, t: "bg", n: "Fundo difuso" }, { a: -100, el: 0, t: "flag", n: "Bandeira" }, { a: 100, el: 0, t: "flag", n: "Bandeira" }],
    light: "bright-field lighting: evenly backlit white diffusion panel, black flags on the sides creating crisp dark outlines on the glass",
    prompt: "Clear glass [bottle] on a glowing white background, bright-field lighting with an evenly backlit diffusion panel and black flags creating crisp dark outlines along the glass edges, clean minimal composition, pharmaceutical advertising aesthetic, f/11" },
  { id: "P4", cat: "produto", nome: "Degradê no fundo", bg: "grad",
    quando: "Cria profundidade e um halo atrás do produto. Deixa a imagem com cara de estúdio e com área limpa para aplicar texto.",
    passos: ["Principal suave sobre o produto.", "Refletor com colmeia (grid) apontado para o fundo, atrás do produto.", "Afaste o produto do fundo para a luz principal não vazar."],
    dica: "Troque o grid por um snoot para um halo pequeno e intenso, ou use gelatina para dar cor.",
    lights: [{ a: -40, el: .5, t: "soft", n: "Principal" }, { a: 170, el: 0, t: "grid", n: "Spot no fundo" }],
    light: "soft key light with a gridded spotlight on the backdrop creating a glowing gradient halo behind the product",
    prompt: "[Product] centered on a seamless backdrop with a soft glowing gradient halo behind it, soft key light from the left, gridded spotlight on the background, generous negative space for copy, elegant commercial studio photography" },
  { id: "P5", cat: "produto", nome: "Contraluz em líquidos", bg: "black",
    quando: "Faz as bebidas brilharem: cerveja, suco, whisky, azeite. A luz atravessa o líquido e acende a cor.",
    passos: ["Luz forte atrás do copo ou garrafa, escondida pelo próprio produto.", "Recorte um cartão branco do tamanho do líquido e cole atrás do vidro.", "Cartão branco na frente para trazer de volta um pouco do rótulo."],
    dica: "Borrife glicerina com água no vidro para criar gotas de condensação que não escorrem.",
    lights: [{ a: 180, el: 0, t: "soft", n: "Contraluz" }, { a: 0, el: 0, t: "refl", n: "Cartão branco", r: .6 }],
    light: "strong backlight shining through the liquid making it glow, subtle white card fill on the label",
    prompt: "Glass of [amber whisky / cold beer] glowing from strong backlight through the liquid, condensation droplets on the glass, subtle front fill on the label, dark moody background, beverage advertising photography, 90mm, f/8" },
  { id: "P6", cat: "produto", nome: "Splash congelado", bg: "black",
    quando: "Gotas, respingos e ingredientes voando, congelados no ar. Energia pura para bebidas, cosméticos e alimentos.",
    passos: ["Duas strips nas laterais traseiras para contornar o líquido.", "Flashes em potência baixa: quanto menos potência, menor a duração do disparo e mais nítido o congelamento.", "Sala escura, e o disparo no pico do respingo."],
    dica: "Faça dezenas de tentativas e junte os melhores respingos na pós-produção.",
    lights: [{ a: -125, el: .2, t: "strip", n: "Strip" }, { a: 125, el: .2, t: "strip", n: "Strip" }, { a: 180, el: 0, t: "bg", n: "Fundo" }],
    light: "high-speed flash lighting with two rear strip lights outlining frozen liquid, crisp freeze motion",
    prompt: "[Product] with a dramatic frozen splash of [liquid] around it, droplets suspended mid-air, high-speed flash freeze, two rear strip lights outlining the liquid crown, dark background, dynamic beverage advertising photography, ultra sharp" },
  { id: "P7", cat: "produto", nome: "Flat lay com luz de janela", bg: "light",
    quando: "Composições vistas de cima: food, moda, kits de produto. Sombra suave e natural, estética de redes sociais.",
    passos: ["Câmera a 90°, bem de cima, com o sensor paralelo à mesa.", "Janela grande ou softbox de um lado só.", "Rebatedor branco do lado oposto para controlar o contraste."],
    dica: "Use elementos repetidos em número ímpar e deixe um respiro em volta do produto principal.",
    lights: [{ a: -90, el: .8, t: "window", n: "Janela" }, { a: 90, el: .3, t: "refl", n: "Rebatedor" }],
    light: "soft directional window light from one side with gentle natural shadows",
    prompt: "Top-down flat lay of [products] arranged on a textured linen surface, soft directional window light from the left with gentle natural shadows, organized composition with breathing room, lifestyle brand photography, 50mm, overhead" },
  { id: "P8", cat: "produto", nome: "Luz dura e sombras gráficas", bg: "color", bgc: "#c9a27a",
    quando: "Estética atual de marcas de moda e beleza: sombras recortadas, cor chapada, cara de sol de verão.",
    passos: ["Flash sem difusor (ou o sol direto), alto e de lado.", "Fundo de cor sólida e saturada.", "Use galhos, persianas ou recortes na frente da luz para desenhar sombras."],
    dica: "Luz dura valoriza textura. Limpe bem o produto, porque cada poeira aparece.",
    lights: [{ a: -60, el: .7, t: "bare", n: "Flash nu" }, { a: -30, el: .8, t: "flag", n: "Gobo / recorte", r: .55 }],
    light: "hard direct sunlight-style flash casting crisp graphic shadows",
    prompt: "[Product] on a solid terracotta color backdrop, hard direct sunlight casting crisp graphic shadows of palm leaves, bold summer mood, saturated colors, minimalist fashion-beauty advertising, sharp focus" },
  { id: "P9", cat: "produto", nome: "Reflexo em acrílico", bg: "black",
    quando: "O produto parece flutuar sobre o próprio reflexo. Tecnologia, joias e cosméticos premium.",
    passos: ["Produto sobre acrílico preto brilhante.", "Softbox grande no alto, em cima do produto.", "Strip atrás para separar a silhueta e iluminar o reflexo."],
    dica: "Baixe a câmera quase até a linha do acrílico: o reflexo fica maior e mais dramático.",
    lights: [{ a: 0, el: 1, t: "soft", n: "Softbox de teto", r: .45 }, { a: 180, el: .2, t: "strip", n: "Strip" }],
    light: "overhead softbox with a rear strip light, product reflected on glossy black acrylic",
    prompt: "[Product] standing on glossy black acrylic with a perfect mirror reflection beneath, overhead softbox and rear strip light, low camera angle, sleek premium tech advertising, deep blacks, high contrast" },
  { id: "P10", cat: "produto", nome: "Gelatinas bicolores", bg: "black",
    quando: "Visual neon e noturno para tech, bebidas, games e música.",
    passos: ["Duas luzes nas laterais, uma com gelatina quente e outra fria (magenta e ciano, laranja e azul).", "Fundo escuro para as cores saturarem.", "Um pouco de fumaça ou haze deixa o feixe visível."],
    dica: "Use cores complementares no círculo cromático e as duas na mesma intensidade.",
    lights: [{ a: -110, el: .2, t: "soft", c: "#ff3d7f", n: "Gel magenta" }, { a: 110, el: .2, t: "soft", c: "#2fd3ff", n: "Gel ciano" }],
    light: "dual colored gel lighting, magenta from the left and cyan from the right, neon mood",
    prompt: "[Product] lit with dual colored gels, magenta from the left and cyan from the right, glowing edges, light haze in the air, dark background, cyberpunk neon mood, tech advertising photography" },
  { id: "P11", cat: "produto", nome: "Light painting", bg: "black",
    quando: "Exposição longa pintando com luz: brilhos contínuos e degradês impossíveis de fazer só com flash. Carros, garrafas, eletrônicos.",
    passos: ["Câmera no tripé, sala totalmente escura, exposição de 5 a 30 s.", "Passe um bastão de LED ou uma lanterna com difusor ao redor do produto.", "Faça várias passadas e junte as melhores em camadas."],
    dica: "Vista roupa preta e não pare de se mover: assim você não aparece na foto.",
    lights: [{ a: -70, el: .3, t: "wand", n: "Bastão em movimento", r: .8 }, { a: 70, el: .3, t: "wand", n: "Bastão", r: .8 }],
    light: "light-painting with a moving LED wand creating smooth continuous highlights and gradients",
    prompt: "[Product] in total darkness sculpted with light painting, smooth continuous highlight streaks and soft gradients along its curves, long exposure, black background, premium automotive-style advertising" },
  { id: "P12", cat: "produto", nome: "Fundo infinito branco", bg: "white",
    quando: "Branco puro e sem sombra: padrão de marketplace, catálogo e site.",
    passos: ["Duas luzes no fundo, cerca de 1 ponto acima do produto, para estourar o branco.", "Duas softboxes na frente, a 45°, iguais.", "Produto afastado do fundo para não pegar vazamento."],
    dica: "Confira o histograma. O fundo deve ficar em 255, mas o produto não pode estourar.",
    lights: [{ a: -35, el: .4, t: "soft", n: "Softbox" }, { a: 35, el: .4, t: "soft", n: "Softbox" }, { a: 160, el: 0, t: "bg", n: "Fundo" }, { a: -160, el: 0, t: "bg", n: "Fundo" }],
    light: "high-key e-commerce lighting: two even front softboxes, pure white blown-out background, no shadows",
    prompt: "[Product] on a pure seamless white background, high-key e-commerce lighting with two even softboxes, no shadows, true-to-life colors, crisp catalog photography, centered, f/11" },

  /* ---------------- EDITORIAL ---------------- */
  { id: "E1", cat: "editorial", nome: "Rembrandt", bg: "dark",
    quando: "Forma um triângulo de luz na bochecha do lado da sombra. Drama, profundidade e retrato de personalidade.",
    passos: ["Luz principal a cerca de 45° do rosto, acima da linha dos olhos.", "Ajuste até a sombra do nariz encontrar a da bochecha.", "Sem preenchimento, ou com um rebatedor bem sutil."],
    dica: "Se o triângulo passa da largura do olho ou do comprimento do nariz, gire a luz um pouco para a frente.",
    lights: [{ a: -45, el: .6, t: "soft", n: "Principal · alta" }],
    light: "Rembrandt lighting, key light 45 degrees above eye level, small triangle of light on the shadow-side cheek",
    prompt: "Editorial portrait of [subject], Rembrandt lighting with a small triangle of light on the shadow-side cheek, dark textured backdrop, painterly mood, rich shadows, 85mm, f/2.8, magazine cover quality" },
  { id: "E2", cat: "editorial", nome: "Borboleta (Paramount)", bg: "grad",
    quando: "Luz alta e frontal que desenha as maçãs do rosto. Beleza e glamour clássico de Hollywood.",
    passos: ["Beauty dish ou softbox acima e bem na frente do rosto.", "A sombra do nariz aparece como uma pequena borboleta embaixo.", "O modelo levanta levemente o queixo."],
    dica: "Funciona melhor em rostos de maçãs marcadas. Em rostos redondos, prefira o loop.",
    lights: [{ a: 0, el: 1, t: "dish", n: "Beauty dish · alto", r: .7 }],
    light: "butterfly Paramount lighting, beauty dish high and centered above the face, sculpted cheekbones",
    prompt: "Glamour beauty portrait of [subject], butterfly Paramount lighting from a high centered beauty dish, sculpted cheekbones, small butterfly shadow under the nose, classic Hollywood elegance, flawless skin, 105mm" },
  { id: "E3", cat: "editorial", nome: "Clamshell", bg: "light",
    quando: "É a borboleta com preenchimento de baixo: pele perfeita e olhos brilhando. Padrão de campanha de beleza.",
    passos: ["Luz principal alta e frontal (dish ou octa).", "Rebatedor ou segunda luz embaixo, na altura do peito, formando uma concha.", "Enquadre por cima das duas fontes."],
    dica: "Os dois reflexos nos olhos (catchlights), em cima e embaixo, são a assinatura do clamshell.",
    lights: [{ a: 0, el: 1, t: "dish", n: "Principal · alta", r: .7 }, { a: 0, el: -1, t: "refl", n: "Rebatedor · baixo", r: .42 }],
    light: "clamshell beauty lighting, high beauty dish with a reflector below, soft even skin, double catchlights",
    prompt: "High-end beauty campaign close-up of [subject], clamshell lighting with a beauty dish above and a reflector below, luminous even skin, double catchlights in the eyes, clean backdrop, cosmetics advertising, 100mm macro" },
  { id: "E4", cat: "editorial", nome: "Loop", bg: "grad",
    quando: "A mais versátil: pequena sombra do nariz em forma de laço. Favorece quase todo rosto.",
    passos: ["Principal de 30° a 45° do rosto, um pouco acima dos olhos.", "A sombra do nariz aponta para o canto da boca, sem tocar a bochecha.", "Preenchimento leve do outro lado."],
    dica: "É um ótimo ponto de partida para retratos corporativos e de LinkedIn.",
    lights: [{ a: -30, el: .5, t: "soft", n: "Principal" }, { a: 60, el: 0, t: "refl", n: "Preenchimento" }],
    light: "loop lighting, softbox 30 degrees off-axis slightly above eye level, gentle fill",
    prompt: "Professional portrait of [subject], loop lighting with a softbox 30 degrees off-axis, gentle fill, soft natural shadows, neutral grey backdrop, confident expression, corporate editorial, 85mm, f/4" },
  { id: "E5", cat: "editorial", nome: "Split", bg: "black",
    quando: "Metade do rosto na luz, metade na sombra: mistério, conflito, capa de disco.",
    passos: ["Uma luz só, a 90° do rosto, na altura dos olhos.", "Use grid para a luz não vazar para o outro lado.", "Fundo escuro."],
    dica: "Vire levemente o rosto para a luz: um reflexo no olho escuro deixa a foto viva.",
    lights: [{ a: -90, el: 0, t: "grid", n: "Grid · 90°" }],
    light: "split lighting, single gridded light at 90 degrees, half the face in deep shadow",
    prompt: "Moody portrait of [subject], split lighting with a single gridded light at 90 degrees illuminating exactly half the face, the other half in deep shadow, black background, mysterious album-cover aesthetic, 85mm" },
  { id: "E6", cat: "editorial", nome: "Flash direto", bg: "light",
    quando: "Estética crua de revista e de rua: sombra dura atrás, pele brilhando e cores saturadas.",
    passos: ["Flash em cima da câmera, apontado direto para o modelo.", "Modelo perto da parede para a sombra ficar recortada.", "Arraste o obturador se quiser o ambiente aparecendo."],
    dica: "Abuse da atitude: essa luz pede poses espontâneas e imperfeitas.",
    lights: [{ a: 0, el: .1, t: "bare", n: "Flash na câmera", r: .75 }],
    light: "direct on-camera flash, hard shadow on the wall behind, glossy skin, saturated colors",
    prompt: "Raw fashion editorial of [subject], direct on-camera flash, hard crisp shadow on the wall behind, glossy skin, saturated colors, spontaneous pose, 2000s magazine party aesthetic, 35mm" },
  { id: "E7", cat: "editorial", nome: "Luz de janela", bg: "light",
    quando: "Suave e natural. Lifestyle, editorial intimista, retrato ambientado.",
    passos: ["Modelo a 1–2 m de uma janela grande, sem sol direto.", "Rosto a 45° da janela.", "Rebatedor do outro lado, se precisar."],
    dica: "Uma cortina fina funciona como um difusor gigante e gratuito.",
    lights: [{ a: -80, el: .3, t: "window", n: "Janela" }, { a: 80, el: 0, t: "refl", n: "Rebatedor" }],
    light: "soft natural window light from the side, gentle falloff",
    prompt: "Intimate lifestyle portrait of [subject] beside a large window, soft natural side light with gentle falloff, muted warm tones, calm authentic moment, editorial magazine feel, 50mm, f/2" },
  { id: "E8", cat: "editorial", nome: "Contraluz golden hour", bg: "warm",
    quando: "Cabelo iluminado, halo quente e flare. Moda, casamento, campanha de verão.",
    passos: ["Fotografe na última hora de sol, com o sol atrás do modelo.", "Rebatedor dourado na frente para iluminar o rosto.", "Deixe entrar um pouco de flare, sem lavar a imagem."],
    dica: "Meça a luz pelo rosto, não pelo céu. O fundo pode estourar.",
    lights: [{ a: 170, el: .2, t: "sun", n: "Sol", r: 1.1 }, { a: 10, el: 0, t: "refl", n: "Rebatedor dourado", c: "#f3b25a" }],
    light: "golden hour backlight with glowing rim on the hair, warm reflector fill, soft lens flare",
    prompt: "Summer campaign portrait of [subject] at golden hour, sun directly behind creating a glowing rim on the hair, warm golden reflector fill on the face, soft lens flare, dreamy warm tones, 85mm, f/1.8" },
  { id: "E9", cat: "editorial", nome: "Kicker com grid", bg: "dark",
    quando: "Uma borda de luz recorta a silhueta: editorial de moda com atitude.",
    passos: ["Principal suave de um lado.", "Luz com grid atrás e do lado oposto, raspando o contorno.", "Fundo escuro para a borda aparecer."],
    dica: "Com o kicker mais forte que a principal, a foto fica mais gráfica e agressiva.",
    lights: [{ a: -40, el: .5, t: "dish", n: "Principal" }, { a: 140, el: .3, t: "grid", n: "Kicker" }],
    light: "fashion lighting with a soft key and a gridded kicker behind creating a crisp rim along the silhouette",
    prompt: "Fashion editorial of [subject] in [outfit], soft key light from the front-left and a gridded kicker light behind right carving a crisp rim along the silhouette, dark backdrop, strong attitude pose, high-fashion magazine, 70mm" },
  { id: "E10", cat: "editorial", nome: "High key", bg: "white",
    quando: "Claro, limpo e otimista: beleza, saúde, lifestyle.",
    passos: ["Fundo branco estourado com duas luzes.", "Principal grande e suave na frente.", "Pouquíssimas sombras e contraste baixo."],
    dica: "Roupas claras mantêm a leveza. Evite preto em high key.",
    lights: [{ a: -30, el: .4, t: "soft", n: "Principal" }, { a: 30, el: .2, t: "soft", n: "Preenchimento" }, { a: 160, el: 0, t: "bg", n: "Fundo" }, { a: -160, el: 0, t: "bg", n: "Fundo" }],
    light: "high-key lighting, bright even soft light, blown-out white background, minimal shadows",
    prompt: "Bright high-key portrait of [subject], soft even lighting, pure white blown-out background, minimal shadows, fresh optimistic mood, clean wellness brand campaign, 85mm" },
  { id: "E11", cat: "editorial", nome: "Low key / chiaroscuro", bg: "black",
    quando: "Quase tudo em sombra e só o essencial iluminado. Luxo, perfume masculino, drama.",
    passos: ["Uma luz com grid, bem direcionada.", "Bandeiras pretas para impedir o rebote.", "Fundo e roupa escuros."],
    dica: "Exponha para as altas luzes e deixe o resto afundar no preto.",
    lights: [{ a: -70, el: .5, t: "grid", n: "Grid" }, { a: 70, el: 0, t: "flag", n: "Bandeira preta" }],
    light: "low-key chiaroscuro lighting, single gridded light, deep blacks, only essential highlights",
    prompt: "Low-key chiaroscuro portrait of [subject], single gridded light sculpting the face, deep black shadows swallowing the rest, luxurious and dramatic, Renaissance painting mood, 85mm" },
  { id: "E12", cat: "editorial", nome: "Arrasto com flash", bg: "night",
    quando: "O flash congela o modelo e a exposição longa borra as luzes em volta. Movimento, noite, música.",
    passos: ["Velocidade de 1/4 a 1 s, ISO baixo.", "Flash na sincronia da segunda cortina.", "Mova a câmera durante a exposição."],
    dica: "Gire a câmera no próprio eixo durante a exposição para ter rastros circulares.",
    lights: [{ a: -20, el: .3, t: "bare", n: "Flash" }, { a: 180, el: .3, t: "amb", n: "Luzes da cidade", r: 1.05 }],
    light: "flash with dragged shutter, subject frozen sharp while city lights streak with motion blur",
    prompt: "Night fashion shot of [subject], rear-curtain flash freezing the subject sharp while colorful city lights streak into motion trails, dragged shutter, energetic nightlife editorial, 35mm" },
  { id: "E13", cat: "editorial", nome: "Fundo com gelatina", bg: "gel", bgc: "#ff4d1c",
    quando: "Uma cor sólida e vibrante atrás, sem pintar o fundo: a identidade da marca dentro da foto.",
    passos: ["Fundo cinza ou branco.", "Luz com grid e gelatina colorida apontada para o fundo.", "Principal neutra no modelo, sem vazar no fundo."],
    dica: "Use a cor principal da marca do cliente. Isso vende a campanha na hora.",
    lights: [{ a: -35, el: .5, t: "soft", n: "Principal" }, { a: 180, el: 0, t: "bg", c: "#ff4d1c", n: "Gel no fundo" }],
    light: "neutral soft key with a colored gel spotlight painting the backdrop in a vivid brand color",
    prompt: "Bold campaign portrait of [subject], neutral soft key light, backdrop painted by a vivid [orange] colored gel with a soft halo, strong brand color identity, modern advertising, 85mm" },

  /* ---------------- COMPOSIÇÃO ---------------- */
  { id: "C1", cat: "composicao", nome: "Regra dos terços", comp: "thirds",
    quando: "O assunto fica numa das interseções: a imagem ganha tensão e equilíbrio natural.",
    passos: ["Ative a grade na câmera.", "Coloque os olhos ou o ponto de interesse numa interseção.", "Deixe espaço na direção em que o assunto olha ou se move."],
    dica: "Regra para aprender e depois quebrar com intenção.",
    light: "rule-of-thirds composition with the subject placed on an intersection",
    prompt: "[Subject] placed on the right third intersection, open space on the left in the direction of their gaze, balanced rule-of-thirds composition" },
  { id: "C2", cat: "composicao", nome: "Espaço negativo para texto", comp: "negative",
    quando: "Essencial em publicidade: área limpa para título, oferta e logo. O diretor de arte vai te agradecer.",
    passos: ["Pergunte ao cliente o formato final (post, banner, outdoor).", "Deixe um lado inteiro limpo, sem textura forte.", "Fotografe também uma versão mais aberta."],
    dica: "Fotografe uma versão horizontal e uma vertical de cada cena.",
    light: "generous negative space on one side reserved for headline copy",
    prompt: "[Product] on the right side of the frame, large clean negative space on the left reserved for headline copy, minimalist advertising layout" },
  { id: "C3", cat: "composicao", nome: "Simetria central", comp: "sym",
    quando: "Força, ordem e luxo. Ótima para produto herói e para arquitetura.",
    passos: ["Câmera exatamente no eixo do assunto.", "Nivele o horizonte e a vertical.", "Use cenário espelhado ou elementos em pares."],
    dica: "Um único elemento fora da simetria vira o ponto de atenção.",
    light: "perfectly symmetrical centered composition",
    prompt: "[Subject] perfectly centered in a symmetrical composition, mirrored elements on both sides, strong central axis, calm luxurious order" },
  { id: "C4", cat: "composicao", nome: "Contra-plongée heroico", comp: "low",
    quando: "Câmera baixa olhando para cima: o assunto vira herói. Esporte, carros, líderes.",
    passos: ["Câmera abaixo da cintura, apontada para cima.", "Use grande-angular para exagerar a perspectiva.", "Céu ou teto limpo como fundo."],
    dica: "Cuidado com a papada. Peça ao modelo para projetar o queixo para a frente.",
    light: "low-angle heroic perspective looking up at the subject",
    prompt: "Low-angle heroic shot looking up at [subject], wide-angle lens exaggerating perspective, clean sky behind, powerful and monumental" },
  { id: "C5", cat: "composicao", nome: "Vista de cima (top-down)", comp: "top",
    quando: "Organização, padrão e grafismo. Food, papelaria, kits, flat lay.",
    passos: ["Câmera a 90° com o sensor paralelo à mesa.", "Monte uma grade ou uma diagonal clara.", "Controle as sombras para todas irem para o mesmo lado."],
    dica: "Um braço articulado ou uma escada firme valem mais que qualquer lente.",
    light: "overhead top-down perspective with a graphic arrangement",
    prompt: "Overhead top-down shot of [items] arranged in a precise graphic grid, flat perspective, bold shapes and colors, editorial still life" },
  { id: "C6", cat: "composicao", nome: "Macro de detalhe", comp: "macro",
    quando: "Mostra textura, material e acabamento: prova de qualidade. Cosmético, joia, tecido, comida.",
    passos: ["Lente macro e f/8–f/16 para ter profundidade.", "Tripé e disparo remoto.", "Focus stacking se precisar de tudo nítido."],
    dica: "Luz rasante (bem lateral) revela a textura. Luz frontal esconde.",
    light: "extreme macro close-up with raking light revealing texture",
    prompt: "Extreme macro close-up of [detail/texture], raking side light revealing every fiber and imperfection, shallow focus falloff, tactile premium material" },
  { id: "C7", cat: "composicao", nome: "Moldura natural", comp: "frame",
    quando: "Portas, janelas, folhagem e arcos emolduram o assunto e dão profundidade e contexto.",
    passos: ["Encontre uma abertura em primeiro plano.", "Posicione o assunto dentro dela.", "Desfoque a moldura para o olhar ir direto ao centro."],
    dica: "Uma moldura escura na frente de um assunto claro guia o olhar na hora.",
    light: "frame-within-a-frame composition through a foreground opening",
    prompt: "[Subject] framed within a dark foreground doorway, frame-within-a-frame composition, soft out-of-focus edges drawing the eye to the center, cinematic depth" },
  { id: "C8", cat: "composicao", nome: "Linhas guia", comp: "lines",
    quando: "Estradas, trilhos, corredores e sombras levam o olhar até o produto.",
    passos: ["Procure linhas que convergem.", "Coloque o assunto no ponto de fuga ou no fim da linha.", "Grande-angular reforça a convergência."],
    dica: "Linhas diagonais dão dinamismo. As horizontais acalmam.",
    light: "strong leading lines converging toward the subject",
    prompt: "[Subject] at the vanishing point of strong converging leading lines, deep perspective corridor, geometric and dynamic composition" },
];

/* Exemplos para o botão "Surpreenda-me" */
const EXAMPLES = [
  { s: "a luxury perfume bottle", l: "on a wet black stone surface", a: "a single droplet slides down the glass", m: "dark, sensual, high-end" },
  { s: "a woman in a red linen dress", l: "on a sunlit Mediterranean rooftop", a: "she walks slowly while the fabric moves in the wind", m: "warm summer editorial" },
  { s: "a cold craft beer can", l: "on a bar counter with neon lights", a: "condensation runs down the can", m: "vibrant nightlife" },
  { s: "a stainless steel wristwatch", l: "floating over black acrylic", a: "the second hand ticks", m: "precise, premium, minimal" },
  { s: "a barista pouring latte art", l: "in a cozy specialty coffee shop", a: "milk swirls into a heart shape", m: "soft morning light, authentic" },
  { s: "a white sneaker", l: "on a concrete skate park ramp", a: "a skater lands a trick", m: "urban, energetic, streetwear" },
];
